### ISSUE TITLE
Failed to export keypoint annotations to coco

### ISSUE THREAD

**Issue by nayemabs** [supervisely-ecosystem/export-to-coco#11]
I want to export keypoint annotations to coco format. However, the app fails to do so with the following not implemented error in the log:
`Info2023.02.02 10:01:48
TASK LOG LEVEL: INFO (20)
Info2023.02.02 10:01:48
TASK_START
Info2023.02.02 10:01:48
TASK_MSG task_type=app, state={"slyProjectId":226389,"slyProjectName":"Goat KPT project","datasets":[],"allDatasets":true,"selectedFilter":"all","selectedOutput":"images"}, appInfo={"id":1014014,"version":"v1.2.5","githubUrl":"https://github.com/supervisely-ecosystem/export-to-coco","moduleId":104,"configDir":"","logLevel":"info","baseUrl":"/net/Eg_CUsrMxWVQBcpGL0mCSWuKIlvw-T0jnqyBn3Mpf6Vlfo4O8y9MuKt7DpWsVHq82KKolFx-5NDhc7VA"}, context={"teamId":68783,"workspaceId":80712,"userId":66334,"userLogin":"nayemabs","apiToken":"***","spawnUserId":66334,"spawnUserLogin":"nayemabs","spawnApiToken":"***"}, instanceVersion=6.7.9, folderToMount=null, instance_type=community, server_address=https://app.supervise.ly, api_token=***, agent_info={"agent_id_from_storage_path":366,"hardware_info":{"psutil":{"cpu":{"count":{"logical_cores":8,"physical_cores":4}},"memory_B":{"physical":33586388992,"swap":0}},"platform":{"uname":["Linux","d90a0d18c8d1","4.15.0-88-generic","#88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020","x86_64","x86_64"]},"cpuinfo":{"models":[" Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz"],"count":{"logical_cores":8,"physical_cpus":1}},"meminfo":{"memory_B":{"physical":33586388992,"swap":0}},"nvidia-smi":null},"agent_image":"supervisely/agent:6.7.8","agent_version":"agent:6.7.8","agent_image_digest":"sha256:276712175183b20e69b7f85a1d2d16075284c2ab2c432ed67aa14d6eead2161e","environ":{"SUPERVISELY_AGENT_FILES":"/root/supervisely/agent-366","DOCKER_NET":"supervisely-net-***"}}, agent_version=agent:6.7.8
Info2023.02.02 10:01:48
Git repo already exists
Info2023.02.02 10:01:48
Repo directory on host dir=/sly_agent/app_sessions/482276/repo
Info2023.02.02 10:01:48
DIRECTORY_TREE tree=/sly_agent/app_sessions/482276/repo
├── [2.3K]  README.md
├── [ 819]  config.json
├── [ 466]  local.env
├── [  22]  requirements.txt
└── [ 104]  src
    ├── [ 804]  convert_geometry.py
    ├── [5.3K]  functions.py
    ├── [1.2K]  globals.py
    ├── [3.1K]  main.py
    └── [1.9K]  modal.html

1 directory, 9 files
Info2023.02.02 10:01:48
App moduleId == 104 [v=v1.2.5] in ecosystem
Info2023.02.02 10:01:48
App config config={"icon":"https://i.imgur.com/9uY44aW.png","author":{"name":"Pavel Bartsits"},"poster":"https://user-images.githubusercontent.com/48913536/183899083-64d7683d-57f9-4f7a-b5f4-bf9e7ffd3246.png","needGPU":false,"headless":true,"categories":["images","export"],"lastCommit":"a32a631da05a63324aa91e92cfa32e4adcc0166b","contextMenu":{"target":["images_project"],"contextRoot":"Download as","contextCategory":null},"description":"Converts Supervisely to COCO format and prepares tar archive for download","main_script":"src/main.py","sessionTags":[],"docker_image":"supervisely/base-py-sdk:6.68.109","taskLocation":"workspace_tasks","defaultBranch":"master","isPrivateRepo":false,"restartPolicy":"never","slyModuleInfo":{"baseSlug":"supervisely-ecosystem/export-to-coco"},"communityAgent":true,"iconBackground":"#FFFFFF","integratedInto":["standalone"],"modal_template":"src/modal.html","instanceVersion":"6.4.57","storeDataOnAgent":false,"modalTemplateState":{"allDatasets":true,"datasets":[],"selectedFilter":"all","selectedOutput":"images"},"modalTemplateContent":"<div>\n  <div v-if=\"!context.datasetId\">\n    <sly-field\n      title=\"Select Datasets\"\n      description=\"Export whole project or select specific datasets in the selector\"\n    >\n      <el-checkbox v-model=\"state.allDatasets\">Export all datasets</el-checkbox>\n\n      <sly-select-dataset\n        v-if=\"!state.allDatasets\"\n        :project-id=\"context.projectId\"\n        :datasets.sync=\"state.datasets\"\n        :options=\"{ multiple: true, valueProperty: 'id' }\"\n      ></sly-select-dataset>\n    </sly-field>\n  </div>\n\n  <div>\n    <sly-field\n      title=\"Filter images\"\n      description=\"Choose whether you want to export all images or only annotated images (that have either labels or tags)\"\n    >\n      <div>\n        <el-radio-group v-model=\"state.selectedFilter\" size=\"normal\">\n          <div>\n            <el-radio label=\"all\"> <span>all images</span></el-radio>\n          </div>\n          <div>\n            <el-radio\n              label=\"annotated\"\n              style=\"display: flex; align-items: center\"\n              ><span style=\"white-space: normal\"\n                >only annotated images (images without annotations will be\n                skipped and will not be presented in the output archive)</span\n              ></el-radio\n            >\n          </div>\n        </el-radio-group>\n      </div>\n    </sly-field>\n\n    <sly-field\n      title=\"Select output\"\n      description=\"Choose between exporting images with annotations or only annotations (.json)\"\n    >\n      <div>\n        <el-radio-group v-model=\"state.selectedOutput\" size=\"normal\">\n          <div>\n            <el-radio label=\"images\">\n              <span>images and annotations</span>\n            </el-radio>\n          </div>\n          <div>\n            <el-radio label=\"annotations\">\n              <span>only annotations (.json)</span></el-radio\n            >\n          </div>\n        </el-radio-group>\n      </div>\n    </sly-field>\n  </div>\n</div>\n","name":"Export to COCO","type":"app"}
Info2023.02.02 10:01:48
Selected docker runtime runtime=runc
Info2023.02.02 10:01:48
LAST_COMPLETE_STEP step=null
Info2023.02.02 10:01:48
BEFORE_STEP step=DOWNLOAD
Info2023.02.02 10:01:48
BEFORE_STEP step=MAIN
Info2023.02.02 10:01:48
Agent ID = 366
Info2023.02.02 10:01:48
✅ To access the app in browser, copy and paste this URL: https://app.supervise.ly/net/Eg_CUsrMxWVQBcpGL0mCSWuKIlvw-T0jnqyBn3Mpf6Vlfo4O8y9MuKt7DpWsVHq82KKolFx-5NDhc7VA
Info2023.02.02 10:01:48
docker_pull_if_needed args policy=ifnotpresent, type(policy)=<enum 'PullPolicy'>
Info2023.02.02 10:01:48
Relative path to requirements: requirements.txt
Info2023.02.02 10:01:48
requirements.txt:
Info2023.02.02 10:01:48
supervisely==6.68.109

Info2023.02.02 10:01:48
Use existing pip cache
Info2023.02.02 10:01:48
Task host data dir dir=/root/supervisely/agent-366/app_data/export-to-coco/482276, moduleId=104, app name=Export to COCO
Info2023.02.02 10:01:48
Docker container volumes volumes={"/root/.supervisely-agent/***/app_sessions/482276":{"bind":"/app","mode":"rw"},"/root/.supervisely-agent/***/apps_cache/68783":{"bind":"/apps_cache","mode":"rw"},"/root/.supervisely-agent/***/storage/apps_pip_cache/104/v1.2.5/pip":{"bind":"/root/.cache/pip","mode":"rw"},"/root/supervisely/agent-366/app_data/export-to-coco/482276":{"bind":"/sly-app-data","mode":"rw"},"/root/supervisely/agent-366":{"bind":"/agent-storage","mode":"rw"}}
Info2023.02.02 10:01:48
Infinite command command=while true; do sleep 30; done;
Info2023.02.02 10:01:49
Docker container is spawned container_id=cf6ad732489ca8119bca88494defb30c71bc448eac5930f5055746ac488725dc, container_name=sly_task_482276_supervisely_ad2128b3badd78b2d65d9f1df5c0b770551106ba1bb03c1dfc98dfb5f50a9a73
Info2023.02.02 10:01:49
Double check pip cache for old agents
Info2023.02.02 10:01:49
Installing app requirements
Info2023.02.02 10:01:49
PIP command: pip3 install --disable-pip-version-check -r /app/repo/requirements.txt
Info2023.02.02 10:01:49
Requirement already satisfied: supervisely==6.68.109 in /usr/local/lib/python3.8/dist-packages (from -r /app/repo/requirements.txt (line 1)) (6.68.109)
Info2023.02.02 10:01:49
Requirement already satisfied: imgaug<1.0.0,>=0.4.0 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.4.0)
Info2023.02.02 10:01:49
Requirement already satisfied: MarkupSafe<3.0.0,>=2.1.1 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (2.1.1)
Info2023.02.02 10:01:49
Requirement already satisfied: opencv-python<5.0.0.0,>=4.5.5.62 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (4.6.0.66)
Info2023.02.02 10:01:49
Requirement already satisfied: requests<3.0.0,>=2.27.1 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (2.28.0)
Info2023.02.02 10:01:49
Requirement already satisfied: protobuf<=3.20.3,>=3.14.0 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (3.14.0)
Info2023.02.02 10:01:49
Requirement already satisfied: SimpleITK<3.0.0.0,>=2.1.1.2 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (2.2.0)
Info2023.02.02 10:01:49
Requirement already satisfied: python-magic<1.0.0,>=0.4.25 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.4.27)
Info2023.02.02 10:01:49
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (4.11.1)
Info2023.02.02 10:01:49
Requirement already satisfied: pillow<10.0.0,>=5.4.1 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (9.2.0)
Info2023.02.02 10:01:49
Requirement already satisfied: psutil<6.0.0,>=5.9.0 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (5.9.2)
Info2023.02.02 10:01:49
Requirement already satisfied: uvicorn[standard]<1.0.0,>=0.18.2 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.18.3)
Info2023.02.02 10:01:49
Requirement already satisfied: scikit-video<2.0.0,>=1.1.11 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.1.11)
Info2023.02.02 10:01:49
Requirement already satisfied: python-dotenv<1.0.0,>=0.19.2 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.21.0)
Info2023.02.02 10:01:49
Requirement already satisfied: python-multipart==0.0.5 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.0.5)
Info2023.02.02 10:01:49
Requirement already satisfied: requests-toolbelt<1.0.0,>=0.9.1 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.9.1)
Info2023.02.02 10:01:49
Requirement already satisfied: jinja2<4.0.0,>=3.0.3 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (3.1.2)
Info2023.02.02 10:01:49
Requirement already satisfied: numerize in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.12)
Info2023.02.02 10:01:49
Requirement already satisfied: distinctipy in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.2.2)
Info2023.02.02 10:01:49
Requirement already satisfied: trimesh<4.0.0,>=3.11.2 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (3.15.3)
Info2023.02.02 10:01:49
Requirement already satisfied: pydicom<3.0.0,>=2.3.0 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (2.3.0)
Info2023.02.02 10:01:49
Requirement already satisfied: jsonpatch<2.0,>=1.32 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.32)
Info2023.02.02 10:01:49
Requirement already satisfied: varname<1.0.0,>=0.8.1 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.10.0)
Info2023.02.02 10:01:49
Requirement already satisfied: pandas<=1.5.2,>=1.1.3 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.1.3)
Info2023.02.02 10:01:49
Requirement already satisfied: pynrrd<1.0.0,>=0.4.2 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.4.3)
Info2023.02.02 10:01:49
Requirement already satisfied: stringcase<2.0.0,>=1.2.0 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.2.0)
Info2023.02.02 10:01:49
Requirement already satisfied: python-json-logger<3.0.0,>=0.1.11 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.1.11)
Info2023.02.02 10:01:49
Requirement already satisfied: async-asgi-testclient in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.4.11)
Info2023.02.02 10:01:49
Requirement already satisfied: PyYAML in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (6.0)
Info2023.02.02 10:01:49
Requirement already satisfied: tqdm<5.0.0,>=4.62.3 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (4.64.1)
Info2023.02.02 10:01:49
Requirement already satisfied: fastapi<1.0.0,>=0.79.0 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.85.0)
Info2023.02.02 10:01:49
Requirement already satisfied: Shapely<2.0.0,>=1.7.1 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.7.1)
Info2023.02.02 10:01:49
Requirement already satisfied: arel<1.0.0,>=0.2.0 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.2.0)
Info2023.02.02 10:01:49
Requirement already satisfied: PTable<1.0.0,>=0.9.2 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.9.2)
Info2023.02.02 10:01:49
Requirement already satisfied: bidict<1.0.0,>=0.21.2 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.21.2)
Info2023.02.02 10:01:49
Requirement already satisfied: websockets<11.0,>=10.3 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (10.3)
Info2023.02.02 10:01:49
Requirement already satisfied: ffmpeg-python==0.2.0 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.2.0)
Info2023.02.02 10:01:49
Requirement already satisfied: numpy<2.0.0,>=1.19 in /usr/local/lib/python3.8/dist-packages (from supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.19.0)
Info2023.02.02 10:01:49
Requirement already satisfied: future in /usr/local/lib/python3.8/dist-packages (from ffmpeg-python==0.2.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.18.2)
Info2023.02.02 10:01:49
Requirement already satisfied: six>=1.4.0 in /usr/lib/python3/dist-packages (from python-multipart==0.0.5->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.14.0)
Info2023.02.02 10:01:49
Requirement already satisfied: starlette==0.* in /usr/local/lib/python3.8/dist-packages (from arel<1.0.0,>=0.2.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.20.4)
Info2023.02.02 10:01:49
Requirement already satisfied: watchgod==0.6.* in /usr/local/lib/python3.8/dist-packages (from arel<1.0.0,>=0.2.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.6)
Info2023.02.02 10:01:50
Requirement already satisfied: typing-extensions>=3.10.0 in /usr/local/lib/python3.8/dist-packages (from starlette==0.*->arel<1.0.0,>=0.2.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (4.3.0)
Info2023.02.02 10:01:50
Requirement already satisfied: anyio<5,>=3.4.0 in /usr/local/lib/python3.8/dist-packages (from starlette==0.*->arel<1.0.0,>=0.2.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (3.6.1)
Info2023.02.02 10:01:50
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in /usr/local/lib/python3.8/dist-packages (from fastapi<1.0.0,>=0.79.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.10.2)
Info2023.02.02 10:01:50
Requirement already satisfied: matplotlib in /usr/local/lib/python3.8/dist-packages (from imgaug<1.0.0,>=0.4.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (3.3.2)
Info2023.02.02 10:01:50
Requirement already satisfied: scikit-image>=0.14.2 in /usr/local/lib/python3.8/dist-packages (from imgaug<1.0.0,>=0.4.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.17.1)
Info2023.02.02 10:01:50
Requirement already satisfied: scipy in /usr/local/lib/python3.8/dist-packages (from imgaug<1.0.0,>=0.4.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.5.2)
Info2023.02.02 10:01:50
Requirement already satisfied: imageio in /usr/local/lib/python3.8/dist-packages (from imgaug<1.0.0,>=0.4.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (2.10.3)
Info2023.02.02 10:01:50
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.8/dist-packages (from jsonpatch<2.0,>=1.32->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (2.3)
Info2023.02.02 10:01:50
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas<=1.5.2,>=1.1.3->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (2.8.2)
Info2023.02.02 10:01:50
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.8/dist-packages (from pandas<=1.5.2,>=1.1.3->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (2021.3)
Info2023.02.02 10:01:50
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0,>=2.27.1->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (2.0.12)
Info2023.02.02 10:01:50
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests<3.0.0,>=2.27.1->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.25.8)
Info2023.02.02 10:01:50
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests<3.0.0,>=2.27.1->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (2.8)
Info2023.02.02 10:01:50
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0,>=2.27.1->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (2021.10.8)
Info2023.02.02 10:01:50
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.8/dist-packages (from uvicorn[standard]<1.0.0,>=0.18.2->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.14.0)
Info2023.02.02 10:01:50
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.8/dist-packages (from uvicorn[standard]<1.0.0,>=0.18.2->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (8.0.3)
Info2023.02.02 10:01:50
Requirement already satisfied: httptools>=0.4.0 in /usr/local/lib/python3.8/dist-packages (from uvicorn[standard]<1.0.0,>=0.18.2->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.5.0)
Info2023.02.02 10:01:50
Requirement already satisfied: watchfiles>=0.13 in /usr/local/lib/python3.8/dist-packages (from uvicorn[standard]<1.0.0,>=0.18.2->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.17.0)
Info2023.02.02 10:01:50
Requirement already satisfied: uvloop!=0.15.0,!=0.15.1,>=0.14.0 in /usr/local/lib/python3.8/dist-packages (from uvicorn[standard]<1.0.0,>=0.18.2->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.17.0)
Info2023.02.02 10:01:50
Requirement already satisfied: executing<2.0,>=1.1 in /usr/local/lib/python3.8/dist-packages (from varname<1.0.0,>=0.8.1->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.1.0)
Info2023.02.02 10:01:50
Requirement already satisfied: multidict<7.0,>=4.0 in /usr/local/lib/python3.8/dist-packages (from async-asgi-testclient->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (6.0.2)
Info2023.02.02 10:01:50
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.8/dist-packages (from beautifulsoup4->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (2.3.2.post1)
Info2023.02.02 10:01:50
Requirement already satisfied: networkx>=2.0 in /usr/local/lib/python3.8/dist-packages (from scikit-image>=0.14.2->imgaug<1.0.0,>=0.4.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (2.5)
Info2023.02.02 10:01:50
Requirement already satisfied: PyWavelets>=1.1.1 in /usr/local/lib/python3.8/dist-packages (from scikit-image>=0.14.2->imgaug<1.0.0,>=0.4.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.1.1)
Info2023.02.02 10:01:50
Requirement already satisfied: pooch>=0.5.2 in /usr/local/lib/python3.8/dist-packages (from scikit-image>=0.14.2->imgaug<1.0.0,>=0.4.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.5.2)
Info2023.02.02 10:01:50
Requirement already satisfied: tifffile>=2019.7.26 in /usr/local/lib/python3.8/dist-packages (from scikit-image>=0.14.2->imgaug<1.0.0,>=0.4.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (2021.11.2)
Info2023.02.02 10:01:50
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib->imgaug<1.0.0,>=0.4.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (0.11.0)
Info2023.02.02 10:01:50
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /usr/local/lib/python3.8/dist-packages (from matplotlib->imgaug<1.0.0,>=0.4.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (2.4.7)
Info2023.02.02 10:01:50
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->imgaug<1.0.0,>=0.4.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.3.2)
Info2023.02.02 10:01:50
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.8/dist-packages (from anyio<5,>=3.4.0->starlette==0.*->arel<1.0.0,>=0.2.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.3.0)
Info2023.02.02 10:01:50
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.8/dist-packages (from networkx>=2.0->scikit-image>=0.14.2->imgaug<1.0.0,>=0.4.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (5.1.0)
Info2023.02.02 10:01:50
Requirement already satisfied: appdirs in /usr/local/lib/python3.8/dist-packages (from pooch>=0.5.2->scikit-image>=0.14.2->imgaug<1.0.0,>=0.4.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (1.4.4)
Info2023.02.02 10:01:50
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from pooch>=0.5.2->scikit-image>=0.14.2->imgaug<1.0.0,>=0.4.0->supervisely==6.68.109->-r /app/repo/requirements.txt (line 1)) (21.2)
Info2023.02.02 10:01:50
Requirements are installed
Info2023.02.02 10:01:50
pip second install for old agents is finished
Info2023.02.02 10:01:50
command to run command=bash -c "export PYTHONPATH="$PYTHONPATH:/app/repo" && python /app/repo/src/main.py"
Info2023.02.02 10:01:50
command is running command=bash -c "export PYTHONPATH="$PYTHONPATH:/app/repo" && python /app/repo/src/main.py"
Info2023.02.02 10:01:52
Input arguments TASK_ID=482276, context.teamId=68783, context.workspaceId=80712, context.projectId=226389, selectedDatasets=[], selectedFilter=all, selectedOutput=images
Info2023.02.02 10:01:52
there is no gui_template field in config.json
Info2023.02.02 10:01:52
App template path: None
Info2023.02.02 10:01:52
App will be running without GUI app_url=https://app.supervise.ly/apps/sessions/482276
Info2023.02.02 10:01:52
Application session is initialized app_url=https://app.supervise.ly/apps/sessions/482276
Info2023.02.02 10:01:52
Starting publisher
Info2023.02.02 10:01:52
Starting consumer
Info2023.02.02 10:01:52
Starting scheduler
Info2023.02.02 10:01:52
processing Anupam B 1.2...
Error2023.02.02 10:01:54
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/supervisely/app/v1/app_service.py", line 312, in handle_message_sync
    self.callbacks[command](
  File "/usr/local/lib/python3.8/dist-packages/supervisely/decorators/profile.py", line 11, in wrapper_timer
    value = func(*args, **kwargs)
  File "/app/repo/src/main.py", line 49, in export_to_coco
    anns = [convert_geometry.convert_annotation(ann, meta) for ann in anns]
  File "/app/repo/src/main.py", line 49, in <listcomp>
    anns = [convert_geometry.convert_annotation(ann, meta) for ann in anns]
  File "/app/repo/src/convert_geometry.py", line 22, in convert_annotation
    converted_labels = lbl.convert(new_cls)
  File "/usr/local/lib/python3.8/dist-packages/supervisely/annotation/label.py", line 727, in convert
    geometries = self.geometry.convert(new_obj_class.geometry_type)
  File "/usr/local/lib/python3.8/dist-packages/supervisely/geometry/geometry.py", line 218, in convert
    raise NotImplementedError(
NotImplementedError: from 'graph' to 'polygon'

main_name=export_to_coco, stack=[
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/dist-packages/supervisely/app/v1/app_service.py", line 312, in handle_message_sync
      self.callbacks[command](
    File "/usr/local/lib/python3.8/dist-packages/supervisely/decorators/profile.py", line 11, in wrapper_timer
      value = func(*args, **kwargs)
    File "/app/repo/src/main.py", line 49, in export_to_coco
      anns = [convert_geometry.convert_annotation(ann, meta) for ann in anns]
    File "/app/repo/src/main.py", line 49, in <listcomp>
      anns = [convert_geometry.convert_annotation(ann, meta) for ann in anns]
    File "/app/repo/src/convert_geometry.py", line 22, in convert_annotation
      converted_labels = lbl.convert(new_cls)
    File "/usr/local/lib/python3.8/dist-packages/supervisely/annotation/label.py", line 727, in convert
      geometries = self.geometry.convert(new_obj_class.geometry_type)
    File "/usr/local/lib/python3.8/dist-packages/supervisely/geometry/geometry.py", line 218, in convert
      raise NotImplementedError(
  NotImplementedError: from 'graph' to 'polygon'
]
Info2023.02.02 10:01:54
App will be stopped due to error
Info2023.02.02 10:01:54
Nacking outstanding messages
Info2023.02.02 10:01:54
Cancelling 0 outstanding tasks
Info2023.02.02 10:01:54
Shutting down ThreadPoolExecutor
Info2023.02.02 10:01:54
Releasing 3 threads from executor
Info2023.02.02 10:01:54
Flushing metrics
Info2023.02.02 10:01:54
Successfully shutdown the APP service.
Fatal2023.02.02 10:01:54
Unexpected exception in main. main_name=main, stack=[
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/dist-packages/supervisely/function_wrapper.py", line 15, in main_wrapper
      main_func(*args, **kwargs)
    File "/app/repo/src/main.py", line 88, in main
      g.my_app.run(initial_events=[{"command": "export_to_coco"}])
    File "/usr/local/lib/python3.8/dist-packages/supervisely/app/v1/app_service.py", line 433, in run
      raise self._error
    File "/usr/local/lib/python3.8/dist-packages/supervisely/app/v1/app_service.py", line 312, in handle_message_sync
      self.callbacks[command](
    File "/usr/local/lib/python3.8/dist-packages/supervisely/decorators/profile.py", line 11, in wrapper_timer
      value = func(*args, **kwargs)
    File "/app/repo/src/main.py", line 49, in export_to_coco
      anns = [convert_geometry.convert_annotation(ann, meta) for ann in anns]
    File "/app/repo/src/main.py", line 49, in <listcomp>
      anns = [convert_geometry.convert_annotation(ann, meta) for ann in anns]
    File "/app/repo/src/convert_geometry.py", line 22, in convert_annotation
      converted_labels = lbl.convert(new_cls)
    File "/usr/local/lib/python3.8/dist-packages/supervisely/annotation/label.py", line 727, in convert
      geometries = self.geometry.convert(new_obj_class.geometry_type)
    File "/usr/local/lib/python3.8/dist-packages/supervisely/geometry/geometry.py", line 218, in convert
      raise NotImplementedError(
  NotImplementedError: from 'graph' to 'polygon'
]
Info2023.02.02 10:01:55
TASK_END exit_status=Task container finished with non-zero status: 1
Info2023.02.02 10:01:55
WAIT_FOR_TASK_LOG
Info2023.02.02 10:01:58
REMOVE_TASK_TEMP_DATA IF NECESSARY exit_status=<TaskApp name='TaskApp-452' pid=1719 parent=7 stopped exitcode=1 daemon>, exit_code=1
Info2023.02.02 10:01:58
TASK_REMOVED exit_status=<TaskApp name='TaskApp-452' pid=1719 parent=7 stopped exitcode=1 daemon>, exit_code=1
© 2023 Supervisely OÜ. Built with [icons8](https://icons8.com/),et al.
[Terms of Service](https://supervise.ly/terms-of-service)
 · 
[Privacy Policy](https://supervise.ly/privacy-policy)`

**Comment by almazgimaev** [comment]
Hello, @nayemabs 
apologies for the delayed response. I assume the issue has already been resolved - you can use the [Export to COCO Keypoints](https://ecosystem.supervisely.com/apps/export-coco-keypoints) app. If you have any questions about ecosystem applications, feel free to ask us in the [Slack channel](https://supervise.ly/slack?_ga=2.62439269.875821852.1702288174-1349189971.1682424248).
